{
    'name': 'Coaching Center ERP',
    'version': '18.0',
    'summary': 'Manage students, batches, and fees for coaching centers',
    'author': 'Mantu Raj',
    'category': 'Education',
    'depends': ['base','product','mail','website'],
    'data': [
        'security/security_groups.xml',
        'security/ir.model.access.csv',
        'data/student_sequence.xml',
        'views/student_views.xml',
        'views/batch_views.xml',
        'views/fee_views.xml',  
        'views/coaching_tutor_views.xml',
        'views/coaching_config_views.xml',
        'views/coaching_tutor_assignment_views.xml',
        'views/coaching_dashboard_views.xml',
        'views/coaching_inquiry_views.xml',
        'views/menu.xml',
        'views/homepage/home_custom.xml',
        'views/header/custom_header.xml',
        'views/login/custom_login_template.xml',
        'views/footer/custom_footer.xml',
        'wizard/batch_update_view.xml',
    ],
    "assets": {
        "web.assets_backend": [
            "coaching_center_erp/static/src/components/**/*.js",
            "coaching_center_erp/static/src/components/**/*.xml",
            "coaching_center_erp/static/src/components/**/*.scss",
            'coaching_center_erp/static/src/scss/custom_header.scss',
        ],
        'web.assets_frontend': [
            'coaching_center_erp/static/src/scss/custom_header.scss',
            'coaching_center_erp/static/src/scss/custom_login_page.scss',
            # 'coaching_center_erp/static/src/scss/custom_login_glass.scss',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
}
